module.exports = {
    OK : 200,
    BAD_REQUEST : 400,
    NOT_AUTHORIZED: 401,
    NOT_FOUND : 404,
    SERVER_ERROR : 500,

    OK_MSG: 'OK',
    SUCCESS_MSG: "SUCCESS",
    ERROR_MSG: "ERROR",
    SERVER_ERROR_MSG: "INTERNAL SERVER ERROR",

    INALID_EMAIL: "EMAIL ALREADY REGISTERED",
    INVALID_CREDENTIALS: "INVALID CREDENTIALS",
    SOMETHING_WENT_WRONG: "SOMETHING WENT WRONG",
    NOT_AUTHORIZED_USER: 'USER NOT AUTHORIZED',

    CONTROLLER: 'CONTROLLER',
    SERVICE: 'SERVICE',
    AUTHENTICATION: 'AUTHENTICATION',
    DATABASE: 'DATABASE',
    RESPONSE: 'RESPONSE',

    ENTRY_LEVEL_LOG: 'ENTRY LEVEL LOG',
    SUCCESS_LEVEL_LOG: 'SUCCESS LEVEL LOG',
    ERROR_LEVEL_LOG: 'ERROR LEVEL LOG',

    EXIST_IN_DATABASE: 'IS ALREADY EXISTING IN DATABASE',

    ERROR_OCCURE_WHILE_ADDING_INVOICE: 'ERROR WHILE ADDING INVOICE',
    BILL_NOT_FOUND: 'BILL NOT FOUND',
    INVOICE_IS_NOT_SAVED: 'INVOICE_IS_NOT_SAVED',

    PRODUCTS_UPDATED_SUCCESSFUL: 'PRODUCTS UPDATED SUCCESSFULLY',
    PRODUCT_UPDATED_SUCCESSFUL: 'PRODUCT UPDATED SUCCESSFULLY',
    PRODUCT_DELETED_SUCCESSFUL: 'PRODUCT DELETED SUCCESSFULLY',
    PRODUCT_NOT_FOUND: 'PRODUCT NOT FOUND',
    
    PARTY_UPDATED_SUCCESSFUL: 'PARTY UPDATED SUCCESSFULLY',
    PARTY_DELETED_SUCCESSFUL: 'PARTY DELETED SUCCESSFULLY',
    PARTY_NOT_FOUND: 'PARTY NOT FOUND',

    USER_NOT_FOUND: 'USER_NOT_FOUND',
    USER_DETAILS_UPDATED: 'USER DETAILS UPDATED',
    USER_DELETED_SUCCESSFULLY: 'USER_DELETED_SUCCESSFULLY',

    ADMIN_UNAUTHORIZED: 'ADMIN_UNAUTHORIZED'
}