module.exports = {
    OK : 200,
    BAD_REQUEST : 400,
    NOT_AUTHORIZED: 401,
    NOT_FOUND : 404,
    SERVER_ERROR : 500,

    OK_MSG: 'OK',
    SUCCESS_MSG: "SUCCESS",
    ERROR_MSG: "ERROR",
    SERVER_ERROR_MSG: "INTERNAL SERVER ERROR",

    INALID_EMAIL: "EMAIL ALREADY REGISTERED",
    INVALID_CREDENTIALS: "INVALID CREDENTIALS",
    SOMETHING_WENT_WRONG: "SOMETHING WENT WRONG",
    NOT_AUTHORIZED_USER: 'USER NOT AUTHORIZED',

    CONTROLLER: 'CONTROLLER',
    SERVICE: 'SERVICE',
    AUTHENTICATION: 'AUTHENTICATION',
    DATABASE: 'DATABASE',
    RESPONSE: 'RESPONSE',

    ENTRY_LEVEL_LOG: 'ENTRY LEVEL LOG',
    SUCCESS_LEVEL_LOG: 'SUCCESS LEVEL LOG',
    ERROR_LEVEL_LOG: 'ERROR LEVEL LOG',
}